# Generated by Django 4.1 on 2022-08-21 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learning_Path',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('trainer_name', models.CharField(max_length=20)),
                ('adderes', models.CharField(max_length=500)),
                ('phone_no', models.CharField(max_length=13, unique=True)),
                ('phone_no_optional', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(max_length=50)),
                ('email_optional', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30, null=True)),
                ('trainer_international', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True)),
                ('trainer_pricing', models.CharField(max_length=1000)),
                ('trainer_course_specialization', models.CharField(max_length=5000)),
                ('trainer_skill_set', models.CharField(max_length=10000)),
                ('trainer_tier', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10)),
                ('trainer_attachment', models.FileField(blank=True, null=True, upload_to='portalapp/static/uploads/')),
                ('trainer_enrolled_with', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portalapp.learning_path')),
            ],
        ),
    ]
